### ISSUE TITLE
Fix reference to local file

### ISSUE THREAD

**Issue by nghamilton** [ConsumerDataStandardsAustralia/java-artefacts#1]
https://github.com/ConsumerDataStandardsAustralia/java-artefacts/blob/8a10996ab53f40b4a95eaff8dfc174569f447569/reference-test/src/main/java/au/org/consumerdatastandards/conformance/Main.java#L15

**Comment by fyang1024** [comment]
Thank you @nghamilton. This file was accidentally added into repo when copied from the cds-conformance repo. It should not have been there. It was written to do some local test and wasn't pushed to github. I will delete the file

**Comment by fyang1024** [comment]
It has now been deleted
