### ISSUE TITLE
API - getTransactionDetail

### ISSUE THREAD

**Issue by nghamilton** [ConsumerDataStandardsAustralia/java-artefacts#10]
TransactionDetail is returning “No Matching Model”
Though the payload is valid.

As raised by @anzbankau:
https://github.com/ConsumerDataStandardsAustralia/engineering/issues/52#issuecomment-539832429

**Comment by fyang1024** [comment]
@anzbankau: is it possible to get the getTransactionDetail payload from you?
That'll help us investigate the issue. Thank you.

**Comment by anzbankau** [comment]
@fyang1024  

Below is a sample of the payload we are testing with:

`{
    "data": {
        "accountId": "1BSv4uXrYDqvGOMbAG92-adc_5zAvKpWB9q1W_yj-cA",
        "transactionId": "ERic5DDiW65VcB_rB2H7cplvlplbdoWRShs7dEAp8SA",
        "isDetailAvailable": true,
        "type": "TRANSFER_INCOMING",
        "status": "POSTED",
        "description": "FUNDS RETURNED FOR 109904               PAYMENT TO Testland Mutual B/S Ltd Finance ' Admin Dept1",
        "postingDateTime": "2015-12-31T00:00:00+11:00",
        "valueDateTime": "2015-12-31T00:00:00+11:00",
        "executionDateTime": "2018-03-13T15:37:44+11:00",
        "amount": "3.60",
        "currency": "AUD",
        "reference": "3026V1099044",
        "extendedData": {
            "payer": "OUT CUSTOMER1",
            "payee": "OFFUS Testing22",
            "extensionUType": "x2p101Payload",
            "x2p101Payload": {
                "extendedDescription": "&#x767C;&#x9001;&#x1F60A;&#x1F60A;"
            },
            "service": "X2P1.01"
        }
    },
    "links": {
        "self": "/cds-au/v1/banking/accounts/1BSv4uXrYDqvGOMbAG92-adc_5zAvKpWB9q1W_yj-cA/transactions/ERic5DDiW65VcB_rB2H7cplvlplbdoWRShs7dEAp8SA"
    },
    "meta": {}
}`

**Comment by fyang1024** [comment]
@anzbankau ,

Thank you for the data. I find the data structure is missing a few fields. 
![tx](https://user-images.githubusercontent.com/20808865/66803429-49c99e80-ef6b-11e9-9921-849049328e02.png)
The fields with null value are not in your data structure.
The fixed version is below
```
{ "data": { "accountId": "1BSv4uXrYDqvGOMbAG92-adc_5zAvKpWB9q1W_yj-cA", "transactionId": "ERic5DDiW65VcB_rB2H7cplvlplbdoWRShs7dEAp8SA", "isDetailAvailable": true, "type": "TRANSFER_INCOMING", "status": "POSTED", "description": "FUNDS RETURNED FOR 109904 PAYMENT TO Testland Mutual B/S Ltd Finance ' Admin Dept1", "postingDateTime": "2015-12-31T00:00:00+11:00", "valueDateTime": "2015-12-31T00:00:00+11:00", "executionDateTime": "2018-03-13T15:37:44+11:00", "amount": "3.60", "currency": "AUD", "reference": "3026V1099044", "merchantName":null,"merchantCategoryCode":null,"billerCode":null, "billerName":null, "crn":null, "apcaNumber":null, "extendedData": { "payer": "OUT CUSTOMER1", "payee": "OFFUS Testing22", "extensionUType": "x2p101Payload", "x2p101Payload": { "extendedDescription": "&#x767C;&#x9001;&#x1F60A;&#x1F60A;", "endToEndId":null, "purposeCode": null }, "service": "X2P1.01" } }, "links": { "self": "/cds-au/v1/banking/accounts/1BSv4uXrYDqvGOMbAG92-adc_5zAvKpWB9q1W_yj-cA/transactions/ERic5DDiW65VcB_rB2H7cplvlplbdoWRShs7dEAp8SA" }, "meta": {} }```

However, this example does help me find a bug in the code, that is, 
Jackson ObjectMapper should be configured with DeserializationFeature.READ_ENUMS_USING_TO_STRING feature so that it can correctly read `X2P1.01` Service enum value. I have put the fix in codegen-attempt branch. It will be available in 1.0.0-RC2 release soon

**Comment by anzbankau** [comment]
Hi @fyang1024 

Our take on optional fields is they can be present and null or not present at all and therefore treated as null as per the standards:

> Optional fields MAY be present but this is not guaranteed. It is also valid for these fields to be present but have a null value. Note that optional fields indicate that data may sometimes not be held by a Data Holder and this is an expected scenario.
And 

> Empty/Null Fields
> An empty field (ie. a field that is not present in a payload) will be considered equivalent with a field that is present with a null value.

keen to get your thoughts?

**Comment by fyang1024** [comment]
Hi @anzbankau 

Thank you for pointing that out. We've confirmed that. 
I've put the fix in codegen-attempt branch. It'll be ready in 1.0.0-RC2 release

**Comment by fyang1024** [comment]
Hi @anzbankau,

Can you please try out the latest code / artefacts and let us know if the issue persists?
