### ISSUE TITLE
Add “x-cds-client-headers” to Get Transactions For Account

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/java-artefacts#104]
May not result in an actual change but not sure.

Details are:
> Add “x-cds-client-headers” to Get Transactions For Account per WBC request. Currently the header is missing in the specification and documentation however it is a mandatory header for this endpoint
> 
> See: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/102

**Comment by vadkor** [comment]
Implemented in the _client_ module for all endpoints. Set if a user agent value exists (true for both _client-cli_ and _integration-test_).
