### ISSUE TITLE
Add x-fapi-interaction-id for Get Customer endpoint

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/java-artefacts#105]
May not result in an actual change but not sure:

Details are:
> Add "x-fapi-interaction-id" as a mandatory response header for the Get Customer endpoint (https://consumerdatastandardsaustralia.github.io/standards/#get-customer). 
> 
> This is a swagger and documentation fix as per the other fapi endpoints.
> 
> Refer to https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/137

**Comment by vadkor** [comment]
Always set for all endpoints to a new UUID.
