### ISSUE TITLE
Remove subTier from BankingProductRateTier

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/java-artefacts#106]
This change results in a v3 of product details...

Remove ``subTier`` ``($ref: '#/definitions/BankingProductRateTier_subTier')`` from ``BankingProductRateTier`` in 

Also update BankingAccount to BankingAccountDetailV2 and BankingProductDetail to BankingProductDetailV2.

See: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/103  
Decision record: https://confluence.csiro.au/display/DSB/Decision+-+Issue+%23103+-+Removal+of+subTier+for+ProductRateTier

**Comment by vadkor** [comment]
Done. BankingAccountDetail retrofitted to use lists of BankingProductDepositRateV1 and BankingProductLendingRateV1.
