### ISSUE TITLE
API - getCustomer

### ISSUE THREAD

**Issue by nghamilton** [ConsumerDataStandardsAustralia/java-artefacts#11]
Basic customer response is getting validated against Customerdetail model and failing. 
According to the standards PhoneNumber, email and physicalAddress can be empty.   

Errors:
Required field 'phoneNumbers' has null value in
`{
  "middleNames" : [ "middleNames" ],
  "firstName" : "firstName",
  "lastName" : "lastName",
  "emailAddresses" : null,
  "occupationCode" : null,
  "prefix" : "",
  "physicalAddresses" : null,
  "suffix" : "",
  "phoneNumbers" : null,
  "lastUpdateTime" : "2019-05-22T00:00:00Z"
}`

Required field 'emailAddresses' has null value in
`{
  "middleNames" : [ "middleNames" ],
  "firstName" : "firstName",
  "lastName" : "lastName",
  "emailAddresses" : null,
  "occupationCode" : null,
  "prefix" : "",
  "physicalAddresses" : null,
  "suffix" : "",
  "phoneNumbers" : null,
  "lastUpdateTime" : "2019-05-22T00:00:00Z"
}`

Required field 'physicalAddresses' has null value in
`{
  "middleNames" : [ "middleNames" ],
  "firstName" : "firstName",
  "lastName" : "lastName",
  "emailAddresses" : null,
  "occupationCode" : null,
  "prefix" : "",
  "physicalAddresses" : null,
  "suffix" : "",
  "phoneNumbers" : null,
  "lastUpdateTime" : "2019-05-22T00:00:00Z"
}`

As raised by @anzbankau:
https://github.com/ConsumerDataStandardsAustralia/engineering/issues/52#issuecomment-539832429

**Comment by fyang1024** [comment]
Hi @anzbankau, https://consumerdatastandardsaustralia.github.io/standards/includes/swagger/cds_full.json says 

> Array is mandatory but may be empty if no phone numbers are held
![phoneNumbers](https://user-images.githubusercontent.com/20808865/66730339-d8231f00-ee9c-11e9-8332-5fd893d656df.png)

So, the value is supposed to be `[]` instead of `null`

The same for emailAddresses and physicalAddresses

**Comment by nghamilton** [comment]
I have confirmed with the Standards team that the mandatory array value is supposed to be [] instead of null.

**Comment by anzbankau** [comment]
Hi @nghamilton @fyang1024 

I think maybe the real issue we are seeing was not clearly articulated, what we are seeing is that these data elements are being checked on a get customer call but they are not part of the get customer API standard, they should only be checked on a detail call.

**Comment by fyang1024** [comment]
Hi @anzbankau 

If it is ResponseCommonCustomer data which includes a CommonPerson or CommonOrganisation, then `phoneNumbers` field should not appear in the data structure at all. The same applies to `emailAddresses` and `physicalAddresses`. Correct me if I am wrong

**Comment by anzbankau** [comment]
Hi @fyang1024 

The request we are sending is for get customer and it does not contain the phoneNumbers, emailAddresses or physicalAddresses fields but the conformance suite is throwing errors specific to ResponseCommonCustomerDetail instead of ResponseCommonCustomer.

**Comment by fyang1024** [comment]
Hi @anzbankau 

The tool cannot send get customer request by itself yet. What you can do now with tool regarding customer is something like
`cds-shell> validate-path customer.json`
How did you use it?

**Comment by anzbankau** [comment]
Following steps we are performing in the conformance testing . 

Customer_001.json :
{
    "data": {
        "customerUType": "person",
        "person": {
            "lastUpdateTime": "2019-05-22T00:00:00Z",
            "firstName": "TEST",
            "lastName": "TEST",
            "middleNames": [
                "TEST"
            ],
            "prefix": "",
            "suffix": ""
        }
    },
    "links": {
        "self": "https://api.anz/cds-au/v1/common/customer"
    },
    "meta": {}
}


validate-path -f /Users/yarramak/Desktop/Conformance-sep/JSON/customer_001.json

Below is the error message returned 

Encountered errors while validating: /Users/yarramak/Desktop/Conformance-sep/JSON/customer_001.json

Required field 'phoneNumbers' has null value in
{
  "middleNames" : [ "TEST" ],
  "firstName" : "TEST",
  "lastName" : "TEST",
  "emailAddresses" : null,
  "occupationCode" : null,
  "prefix" : "",
  "physicalAddresses" : null,
  "suffix" : "",
  "phoneNumbers" : null,
  "lastUpdateTime" : "2019-05-22T00:00:00Z"
}

Required field 'emailAddresses' has null value in
{
  "middleNames" : [ "ANTHONY" ],
  "firstName" : "STUART",
  "lastName" : "HARTLEY",
  "emailAddresses" : null,
  "occupationCode" : null,
  "prefix" : "",
 "physicalAddresses" : null,
  "suffix" : "",
  "phoneNumbers" : null,
  "lastUpdateTime" : "2019-05-22T00:00:00Z"
}

Required field 'physicalAddresses' has null value in
{
  "middleNames" : [ "ANTHONY" ],
  "firstName" : "STUART",
  "lastName" : "HARTLEY",
  "emailAddresses" : null,
  "occupationCode" : null,
  "prefix" : "",
  "physicalAddresses" : null,
  "suffix" : "",
  "phoneNumbers" : null,
  "lastUpdateTime" : "2019-05-22T00:00:00Z"
}

**Comment by fyang1024** [comment]
Thank you @anzbankau for sending the test data. It is a bug. Basically there are two potential models in this case, ResponseCommonCustomer and ResponseCommonCustomerDetail. The payload validator used to find any matching model and do the validation. Now it goes through all possible matching models and find the best one. The fix is in codegen-attempt branch now.
It will be ready in 1.0.0-RC2 release

**Comment by fyang1024** [comment]
Hi @anzbankau,

Can you please try out the latest code / artefacts and let us know if the issue persists?
