### ISSUE TITLE
What is the suggested approach for automation with the client cli?

### ISSUE THREAD

**Issue by millent** [ConsumerDataStandardsAustralia/java-artefacts#118]
Hi Team

I am trying to help our testing team to automate the conformance testing of our Open Banking implementation (@CBA). I have had a look at the docker image `consumerdatastandardsaustralia/client-cli:1.3.0` - it provides an interactive shell to excute commands (or even scripts). 

Howerver, I don't see a direct method of automating these interactions - is there another intended way to invoke this cli? 

My initial idea when I heard about this `cli` was that it would present a command line tool which can be called from scripts with paramerters. This would have allowed me to build another docker image which will use the `client-cli` image as a base and then add my own scripts that will invoke the cli ...  

Any advice would be highly appreciated!

Best regards

Millen 
Senior Software Engineer, 
Open Banking
Commonwealth Bank of Australia

**Comment by millent** [comment]
OK, have found that the `client-cli` can be invoked with a script as a parameter like 
```
# /usr/local/openjdk-8/bin/java  -jar /opt/cds-java-artefacts/client-cli.jar @/test/cds-script-01.txt > /test/out.txt
```
where `/test/cds-script-01.txt` is a file containing script commands. 
eg
```
get-log-level
list-payload-models
quit
``` 

This is almost a complete way to automate, however, the `quit` command does not actually exit the process - there seem to be some lingering background threads.

One brute force approach might be to add the `ps` command to the image and kill the process after it executes ... but maybe we could have a cleaner way to shut down?

Any help really appreciated ...

**Comment by vadkor** [comment]
Yes, `quit` doesn't completely end the application now - the embedded web server threads are preventing it from shutting down fully.
We can have a look into this, but we also encourage people to fork the repo, work on the fixes and improvements and submit cross-repo pull requests.

**Comment by vadkor** [comment]
quit/exit perform the full JVM shutdown in Client CLI in the latest release of java-artefacts (1.4.0)
