### ISSUE TITLE
Integration tests do not support ProductsV3

### ISSUE THREAD

**Issue by deboraelkin2** [ConsumerDataStandardsAustralia/java-artefacts#121]
**Description**
The integration tests for BankingProducts set the x-v header to 1 and/or 2. No tests available for ProductsV3 as specified in V1.4 of the standards

**Comment by vadkor** [comment]
@deboraelkin2 Please clone the repo and write the tests. We will review your pull request.

**Comment by vadkor** [comment]
BankingProduct V3 has no differences from BankingProductV2, so there was no point in having a separate class and its own test.

**Comment by deboraelkin2** [comment]
Problem is that the current tests fail when testing against an endpoint that implements ProductsV3 (Tests send x-v=1 or 2, where as a 1.4 compliant endpoint only accepts x-v=3)

**Comment by vadkor** [comment]
Please provide more details on what actually fails. We can't reproduce any test failures.

**Comment by deboraelkin2** [comment]
Rerunning the test suite I noticed that there are some tests for Get Products and GetProductDetails, with x-v=3, which pass in my case. 
The summary at the end only reports tests that fail (in my case, when x-v = 1 or 2, as is expected), but not the cases that succeed. 
You can only see those by scrolling through all the test activity.
