### ISSUE TITLE
Where to get "x-cds-client-headers" and how to get we don't have any idea?

### ISSUE THREAD

**Issue by gobi-it** [ConsumerDataStandardsAustralia/java-artefacts#127]
How and where to get below **headers**

x-fapi-interaction-id: string
x-fapi-auth-date: string
x-fapi-customer-ip-address: string
x-cds-client-headers: string

The get account API we need to pass those info and how?

**Comment by JamesMBligh** [comment]
Hi @gobi-it, is this a specific question for the java artefacts or is it a more general question regarding the standards?

If it is a question about the code in this repo then it would be good if you could elaborate on your question a bit more as it isn't clear exactly what you're after.

If it is a question relating more to the standards then I would recommend asking your question on the [CDR support portal](https://cdr-support.zendesk.com/hc/en-us).

**Comment by CDR-API-Stream** [comment]
Hi @gobi-it ,

We note that you have raised this via the CDR Support Portal. The following response was provided: The requirements for x-cds-client-headers can be found here: https://consumerdatastandardsaustralia.github.io/standards/index.html#http-headers

Further details are also available here: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/104

We will close this issue, thank you for your question.

Thanks,
