### ISSUE TITLE
Suggestion: Automated Docker builds

### ISSUE THREAD

**Issue by LukePrior** [ConsumerDataStandardsAustralia/java-artefacts#134]
I see that you offer a Dockerfile for client-cli, might I suggest you setup GitHub Actions to automatically generate Docker images?

You can see a GitHub Action to do this here: https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by vadkor** [comment]
Docker images are generated by the Maven build. Unlike The Comparator, the java-artefacts build is not triggered by merging into the master branch by design.
