### ISSUE TITLE
Schema validation of Data61 apis 

### ISSUE THREAD

**Issue by swetaiyer** [ConsumerDataStandardsAustralia/java-artefacts#136]
### Hypothesis
Need a recommended method to validate the banking and common api responses against the cds standards

### Description
So far we have been using the docker client-cli image (tag 1.0.0) to help us validate the output of banking and common apis.  
https://hub.docker.com/layers/consumerdatastandardsaustralia/client-cli/1.0.0-SNAPSHOT/images/sha256-79bc56af90303c8dc502891f9402c839558b73966fc1e11e526ca0dd9cec8bd9?context=explore
We are noticing that the later versions of this docker image are not being consistent in flagging if the API response is conformant to the standards. 

### Available Options
We would like to know what is the recommended way to run a schema validation of our API output using the artefacts that are being built for consumer data standards.

**Comment by tom-schier** [comment]
@swetaiyer You could use our postman collection found  [here](https://github.com/ConsumerDataStandardsAustralia/dsb-schema-tools). There is some documentation in there how to use it.

**Comment by swetaiyer** [comment]
Thanks for your response @tom-schier - I will give that a go. I ll close this issue once I have tried it out.

**Comment by swetaiyer** [comment]
This is great! Thank you for sharing the info :)
