### ISSUE TITLE
Test Harness Intended Usage

### ISSUE THREAD

**Issue by fahadbinrahat** [ConsumerDataStandardsAustralia/java-artefacts#15]
**Clarification Sought**

"_Test Harness - A set of automated tests to provide a validation reporting to a Data Holder in line with the future regulatory expectations_" - Quoted from [here](https://consumerdatastandardsaustralia.github.io/engineering/artefacts/index.html) 

Need clarifications on above statement to find real value of this harness. 

- Also, my assumption is, the harness above statement is referring to is this repository only (i.e. cds-conformance)? 

This clarification is needed because readme file of this repository has a very narrow purpose and doesn't align with above statement.

- Does this mean that participants are encouraged to use this repo to check conformance of their APIs such as for self-assessments and/or to make it part of their CI/CD practices?

- Data61 will maintain and keep this harness up to date?

- Data61 will use this harness to perform any official conformance tests of participants APIs?

- What is the overall scope of this test harness? What future regulatory expectations will it cover? only payloads or performance testing aspects as well?

**Comment by fyang1024** [comment]
Hi @fahadbinrahat , thank you for raising the question and sorry for no response until now.
cds-conformance repo is archived. All the java artefacts are consolidated into this repo, hence I tranferred the issue here. 
Hi @nghamilton and @louistaborda, would you please answer this question, as I think you might have more insights than me?

**Comment by nghamilton** [comment]
A few comments in answer to the above questions:

 * All artefacts produced by the Engineering team are now found entirely within this repo ('java-artefacts'), which includes the testing framework found in the `reference-test` folder.

* Participants are encouraged to use (and build upon) tools in this repo to assist in validating their own software. For example, the `reference-test` tool has the feature to validate payloads returned from DHs and confirm that they are structurally correct.

* The tools are not intended to warrant conformance to the Standards, but rather are an aid for self-assessment. The Data Standards Body develops the reference implementation and associated software tools as examples to inform our standards development and also to help educate the technical audience that works with our standards.  We currently expect to continue to develop and maintain this software as the standards evolve.

* This software is open source and provided “as is” for the CDR community.  The Data Standards Body does not define rules, regulations, accreditation criteria, or conformance tests for the CDR regime.
