### ISSUE TITLE
Header validation incorrect in product detail API response check

### ISSUE THREAD

**Issue by NationalAustraliaBank** [ConsumerDataStandardsAustralia/java-artefacts#17]
**Description**
The `Content-Type` header is checked in 2 different ways while running the conformance tests and they both differ in the way the header's value is checked.
In the tests for `/products` endpoint, the header is checked as `startsWith` and in the tests for `/products/{id}`, it is checked with `equals`. 
The check should ideally be the same and should use `startsWith` to ensure that `charset` values within the header value does not break the conformance tests.

**Comment by fyang1024** [comment]
Hi @National Australia Bank, thank you for raising the issue and sorry for no response until now.
cds-conformance repo is archived and all the java artefacts are consolidated into this repo.
I have adopted https://github.com/ConsumerDataStandardsAustralia/cds-conformance/pull/22 and the code change is in codegen-attempt branch. It will be ready in 1.0.0-RC2 release

**Comment by fyang1024** [comment]
This is fixed now @NationalAustraliaBank . Please checkout the latest code and let us know if the issue persists or close this issue if not.
