### ISSUE TITLE
POM having incorrect reference to a dependency

### ISSUE THREAD

**Issue by fahadbinrahat** [ConsumerDataStandardsAustralia/java-artefacts#18]
**Description**
Typo in POM file

**Related Work Items**
Please fix references to surefire plugin in POM file. its mistakenly referring to surefile.

Thanks
    - ConsumerDataStandardsAustralia/cds-conformance#1

**Comment by fyang1024** [comment]
Hi @fahadbinrahat, thank you for raising the issue and sorry for no response until now. cds-conformance repo is archived now. All the java artefacts are consolidated into this repo. I believe this has been fixed for while. I am going to close it now.
