### ISSUE TITLE
Client does not work when proxy is set

### ISSUE THREAD

**Issue by fyang1024** [ConsumerDataStandardsAustralia/java-artefacts#2]
**Description**
When a proxy is set on client CLI, the same exception is thrown as below https://github.com/square/okhttp/issues/2738#issuecomment-515960916

Not clear if it's OkHttpClient issue, or Proxy issue, or client code issue

**Related Work Items**
Where applicable please supply a list of related work items (using #issue format):
    - #1

**Comment by fyang1024** [comment]
CBA has confirmed the proxy setting works on their end. It looks the testing proxy issue instead of code issue.

**Comment by mhanci92** [comment]
@fyang1024 The last few days I kept getting the same "IOException: unexpected end of stream on" error on an irregular basis when setting a proxy for my OkHttpClient. There still seems seems to be an issue regarding Proxy's with newest Version of okhttp (4.4.1)..

**Comment by vadkor** [comment]
@mhanci92 We don't use version 4.4.1 of okhttp. I suggest you raise this issue with okhttp directly.
