### ISSUE TITLE
codegen data-holder output

### ISSUE THREAD

**Issue by s-wickham** [ConsumerDataStandardsAustralia/java-artefacts#21]
Hi,

I have generated a Data Holder by making the following change to the first line of the toClientOptInput() method of the Configuration.java class:
```
//FROM:
//CodeGeneratorConfigcodeGeneratorConfig=CodeGeneratorConfigLoader.forName(getLang());
//TO:
CodeGeneratorConfigcodeGeneratorConfig=CodeGeneratorConfigLoader.forName("data-holder");
```

The command to generate the code was executed with the following arguments:
```-g CodeGenerator -o <output path>```

Following this, I have opened the generated code in intelliJ by selecting the pom.xml file.

Currently a couple of observations have been made by inspecting the generated code and comparing with the existing data-holder that has been generated:
- the classes/packages for the 'utils', 'services', 'repositories' are not generated
- the generated classes do not have the dependencies imported (e.g. annotations)
- missing values
- missing properties, and other missing files in the 'resources'

Is there a set of steps that are available for running the generated code once it has been generated?

Thanks!

**Comment by s-wickham** [comment]
I have posted the reason for the edit to the source code in the issue through the below URL:
https://github.com/ConsumerDataStandardsAustralia/java-artefacts/issues/22

**Comment by fyang1024** [comment]
Thank you @s-wickham for the feedback. 
As I commented on issue #22, codegen is work-in-progress now. These issues will be fixed in next couple of weeks.

**Comment by cdswizard** [comment]
thanks!

**Comment by vadkor** [comment]
CodeGen is decommissioned.
