### ISSUE TITLE
codegen "-g CodeGenerator " null pointer exception

### ISSUE THREAD

**Issue by s-wickham** [ConsumerDataStandardsAustralia/java-artefacts#22]
Hi,

When running the current container that's built for the codegen with the command line arguments:
```
-g CodeGenerator -o <output path>
```
The following error is encountered:
```
12:16:25.521 ERROR [main] [a.o.c.c.CodegenCLI](CodegenCLI.java:70) null
java.lang.NullPointerException: null
	at java.lang.String.concat(String.java:2027)
	at au.org.consumerdatastandards.codegen.code.CodeGeneratorConfigLoader.forName(CodeGeneratorConfigLoader.java:25)
	at au.org.consumerdatastandards.codegen.code.Configurator.toClientOptInput(Configurator.java:24)
	at au.org.consumerdatastandards.codegen.code.CodeGenerator.generate(CodeGenerator.java:57)
	at au.org.consumerdatastandards.codegen.CodegenCLI.main(CodegenCLI.java:64)
```

I have found that editing the first line of the toClientOptInput() method from the Configurator class resolves this issue:
```
//FROM:
//CodeGeneratorConfig codeGeneratorConfig = CodeGeneratorConfigLoader.forName("getLang()");
//TO:
CodeGeneratorConfig codeGeneratorConfig = CodeGeneratorConfigLoader.forName("data-holder");
```
Then the issue is resolved, however is there a parameter that should be provided through the command line that avoids this NullPointerException instead?

Thanks

**Comment by fyang1024** [comment]
Thank you @s-wickham for trying out and raising the issue. codegen artefact is the least mature one compared to others. It's work-in-progress now.

To answer your question, the command line does take -cgt parameter
`-g CodeGenerator  -cgt data-holder -o <output path>` should work.
README.md will be updated to describe the parameters and usage.
Meanwhile, you can probably have a look at `CodeGeneratorOptions` class.

**Comment by vadkor** [comment]
CodeGen is decommissioned.
