### ISSUE TITLE
Add CLI parameter to specify which payload is being validated

### ISSUE THREAD

**Issue by nghamilton** [ConsumerDataStandardsAustralia/java-artefacts#23]
**Description**
Currently the type of a user supplied payload is ascertained dynamically by the test tool, based on the contents of the payload. This can lead to confusing error messages when the user supplies an non-conformant payload.

The payload tool requires a new parameter that lets the user specify the type of the payload they are attempting to validate. (e.g --payloadType <payload name>)

A second parameter should also be created to support the current "best guess" functionality. This will allow users to continue to test either whole or partial payloads. (e.g. --automatic-payload-typing)

These two parameters must be mutually exclusive.

**Comment by fyang1024** [comment]
Now user can add an extra param (e.g, `-m ResponseBankingProductById`) to specify the target model of the payload file. The tool will do automatic payload - model match without the extra param.
Also a new command `list-payload-models` is added to list all the top level payload models (responses of the end points)
