### ISSUE TITLE
Add documentation for running codegen

### ISSUE THREAD

**Issue by nghamilton** [ConsumerDataStandardsAustralia/java-artefacts#25]
**Description**
Need a brief description of the command-line parameters that are required to run the AbstractGenerator (code comment?).

**Comment by perlboy** [comment]
Or just update the doc: https://consumerdatastandardsaustralia.github.io/engineering/artefacts/support/codegen/index.html

**Comment by fyang1024** [comment]
> Or just update the doc: https://consumerdatastandardsaustralia.github.io/engineering/artefacts/support/codegen/index.html

Thanks dude. The whole engineering doc hasn't been updated since Jul. We'll have to do that as a big task.

**Comment by perlboy** [comment]
![image](https://user-images.githubusercontent.com/4291448/68172455-b284c380-ffcb-11e9-81fc-916e1d058205.png)

👍

**Comment by vadkor** [comment]
CodeGen is decommissioned.
