### ISSUE TITLE
Validation of BankingTransactionDetail Schema fails with message 'No matching model found'

### ISSUE THREAD

**Issue by sushmanprasad** [ConsumerDataStandardsAustralia/java-artefacts#28]
1. Validation of BankingTransactionDetail Schema fails with message 'No matching model found'
2. Following are the contents of the JSON file that was used for validation:

{
  "accountId": "string",
  "transactionId": "string",
  "isDetailAvailable": true,
  "type": "FEE",
  "status": "PENDING",
  "description": "string",
  "postingDateTime": "string",
  "valueDateTime": "string",
  "executionDateTime": "string",
  "amount": "string",
  "currency": "string",
  "reference": "string",
  "merchantName": "string",
  "merchantCategoryCode": "string",
  "billerCode": "string",
  "billerName": "string",
  "crn": "string",
  "apcaNumber": "string",
  "extendedData": {
    "payer": "string",
    "payee": "string",
    "extensionUType": "x2p101Payload",
    "x2p101Payload": {
      "extendedDescription": "string",
      "endToEndId": "string",
      "purposeCode": "string"
    },
    "service": "X2P1.01"
  }
}

**Comment by fyang1024** [comment]
Hi @sushmanprasad thank you for raising the issue. This is the same issue as #10 
The code fix is in codegen-attempt branch and the fix will be ready in 1.0.0-RC2 release

**Comment by fyang1024** [comment]
Hi @sushmanprasad please try out the latest code/artefacts to see if the issue persists. If not, please close this issue. thank you
