### ISSUE TITLE
Validation of ResponseBankingTransactionById Schema fails with message 'No matching model found'

### ISSUE THREAD

**Issue by sushmanprasad** [ConsumerDataStandardsAustralia/java-artefacts#30]
1. Validation of ResponseBankingTransactionById fails with message 'No matching model found'
2. Following are the contents of the JSON file that was used for validation:

{
  "data": {
    "accountId": "string",
    "transactionId": "string",
    "isDetailAvailable": true,
    "type": "FEE",
    "status": "PENDING",
    "description": "string",
    "postingDateTime": "string",
    "valueDateTime": "string",
    "executionDateTime": "string",
    "amount": "string",
    "currency": "string",
    "reference": "string",
    "merchantName": "string",
    "merchantCategoryCode": "string",
    "billerCode": "string",
    "billerName": "string",
    "crn": "string",
    "apcaNumber": "string",
    "extendedData": {
      "payer": "string",
      "payee": "string",
      "extensionUType": "x2p101Payload",
      "x2p101Payload": {
        "extendedDescription": "string",
        "endToEndId": "string",
        "purposeCode": "string"
      },
      "service": "X2P1.01"
    }
  },
  "links": {
    "self": "string"
  },
  "meta": {}
}

**Comment by sushmanprasad** [comment]
NOTE: Validation was carried out on 15th October version of Java-Artefacts

**Comment by fyang1024** [comment]
This duplicates #28. I'll close this one.
