### ISSUE TITLE
TLS-MA and refresh token support

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/java-artefacts#48]
Currently, we are using Data61’s client-cli tool to perform file based payload testing. In order to test our APIs more fully by connecting through our security infrastructure, the following enhancements are needed:

1. Support for TLS-MA with test client certificates for both [client-cli](https://github.com/ConsumerDataStandardsAustralia/java-artefacts/tree/master/client-cli/) and [reference-test](https://github.com/ConsumerDataStandardsAustralia/java-artefacts/tree/master/reference-test) - our security infrastructure build assumes that clients will connect with this method as required by the standards.

2. Support for both refresh tokens and access tokens in [reference-test](https://github.com/ConsumerDataStandardsAustralia/java-artefacts/tree/master/reference-test) and [client-cli](https://github.com/ConsumerDataStandardsAustralia/java-artefacts/tree/master/client-cli/). Support for refresh tokens is needed to allow testing without additional custom build for us. This is because of the short lifetime of access tokens and the need to copy tokens between testing infrastructure and security infrastructure.

**Comment by nghamilton** [comment]
This enhancement request is under review: it is being considered for implementation prior to the Jan30 release.

**Comment by fyang1024** [comment]
Working on TLS-MA support in client / client-cli

**Comment by fyang1024** [comment]
It's done now and available in 1.0.0 release.
