### ISSUE TITLE
Client-cli validate-path does not match ResponseBankingAccountsBalanceList unless optional amortisedLimit field is included.

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/java-artefacts#54]
**Description**
The `validate-path` command in client-cli produces the error `1. No matching model found. Specifying a target model will produce more informative errors` for payloads containing a `ResponseBankingAccountsBalanceList` object wherever the optional `amortisedLimit` is not present. This is verifiable by removing the `amortisedLimit` field from the [sample payload for Get Bulk Balances](https://consumerdatastandardsaustralia.github.io/standards/#get-bulk-balances)  in the HTML documentation.

**Comment by fyang1024** [comment]
I cannot reproduce the issue with latest code in dev branch. Since we are releasing dev branch code soon, this issue is deemed to be fixed.
![validate-path-3](https://user-images.githubusercontent.com/20808865/69836111-b0e0af80-129a-11ea-9800-c2abbbb099bf.png)
