### ISSUE TITLE
AmountString validator incorrectly assumes that account numbers have 9 digits

### ISSUE THREAD

**Issue by WestpacOpenBanking** [ConsumerDataStandardsAustralia/java-artefacts#56]
**Description**
The validate-path command in client-cli produces the error `1. maskedNumber 'xxx-xxx xx3416' does not conform to CDS type MaskedAccountString` for payloads containing a `ResponseBankingAccountsList` object even though this is a valid `AmountString`. Similarly 'xxx-xxx xxxx3416' is valid but rejected. A `maskedNumber` value of 'xxx-xxx xxxxx3416' is not rejected – it appears that the tool assumes account numbers are always 9 digits. This varies by bank. Westpac in particular has account numbers with six digits.

For example the file test.json
```json
{ 
  "data": {
    "accounts": [
      {
        "accountId": "string",
        "creationDate": "string",
        "displayName": "string",
        "nickname": "string",
        "openStatus": "OPEN",
        "isOwned": true,
        "maskedNumber": "xxx-xxx xx6516",
        "productCategory": "TRANS_AND_SAVINGS_ACCOUNTS",
        "productName": "string"
      }
    ]
  },
  "links": {
    "self": "string",
    "first": "string",
    "prev": "string",
    "next": "string",
    "last": "string"
  },
  "meta": {
    "totalRecords": 0,
    "totalPages": 0
  }
}
```
Produces the output:
```
Validating /(omitted)/test.json
Found matching model ResponseBankingAccountList
Encountered errors while validating: /(omitted)/test.json

1. maskedNumber 'xxx-xxx xx6516' does not conform to CDS type MaskedAccountString. See below:
{
  "accountId" : "string",
  "creationDate" : "string",
  "displayName" : "string",
  "nickname" : "string",
  "openStatus" : "OPEN",
  "isOwned" : true,
  "maskedNumber" : "xxx-xxx xx6516",
  "productCategory" : "TRANS_AND_SAVINGS_ACCOUNTS",
  "productName" : "string"
}
```

**Comment by fyang1024** [comment]
Hi there, thank you for raising this. ANZ raised the same issue. After discussion with standards team, we will loosen the validation rule. The fix will be released soon. btw, It's not about AmountString but MaskedAccountString
