### ISSUE TITLE
CDS Conformance test incorrectly report missing first and last page links in one page responses

### ISSUE THREAD

**Issue by nghamilton** [ConsumerDataStandardsAustralia/java-artefacts#7]
Re-posting issue #23 from archived cds-conformance tool repo. 

Originally opened by @deboraelkin2 in:
https://github.com/ConsumerDataStandardsAustralia/cds-conformance/issues/23

And mentioned in:
https://github.com/ConsumerDataStandardsAustralia/engineering/issues/52#issuecomment-539374739

**Comment by fyang1024** [comment]
Fixed in codegen-attempt branch.
