### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by nghamilton** [ConsumerDataStandardsAustralia/java-artefacts#8]
command “mvn clean spring-boot:run” failing for . ../java-artefacts/data-holder with the error:

An exception occurred while running. null: InvocationTargetException: java.io.CharConversionException: Invalid UTF-32 character 0x42746431 (above 0x0010ffff) at char #1, byte #7) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.5.RELEASE:run (default-cli) on project data-holder: An exception occurred while running. null

As raised by @anzbankau:
https://github.com/ConsumerDataStandardsAustralia/engineering/issues/52#issuecomment-539832429

**Comment by vadkor** [comment]
Cannot reproduce.
Even though the artifacts are deployed in the maven central repository, it's a good idea to run `mvn clean install` in the parent (java-artefacts) directory once before running `mvn spring-boot:run` in the data-holder directory. No need to `clean` in the data-holder directory afterwards.

**Comment by fyang1024** [comment]
@anzbankau, I cannot reproduce it either. This exception should have been thrown by jackson when reading data from files under payloads/products folder within data-holder module. Please check if there is any change to the files. Meanwhile I have upgraded jackson version from 2.9.9 to 2.9.10 to see if any bug fix in the new version can solve this issue. 
The change has been made in codegen-attempt branch and will be ready in 1.0.0-RC2 release.

**Comment by fyang1024** [comment]
hi @anzbankau

We've just released 1.0.0-RC2. Can you please checkout the latest code in master and see if the issue persists?
