### ISSUE TITLE
API - GetBalance

### ISSUE THREAD

**Issue by nghamilton** [ConsumerDataStandardsAustralia/java-artefacts#9]
GetBalance payload is failing in CDS payload validation with below error when ‘meta object is not present. But as per Specs ‘meta‘ is an optional field.

As raised by @anzbankau:
https://github.com/ConsumerDataStandardsAustralia/engineering/issues/52#issuecomment-539832429

**Comment by fyang1024** [comment]
It's fixed in codegen-attempt branch now and the fix will be ready in 1.0.0-RC2 release

**Comment by fyang1024** [comment]
Hi @anzbankau,

Can you please try out the latest code / artefacts and let us know if the issue persists?
